--- #YAML:1.0
name:               Net-Libdnet
version:            0.95
abstract:           binding for Dug Song's libdnet
author:
    - GomoR <gomor-cpan_at_gomor.org>
license:            bsd
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Gomor:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
