# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./nonblockserver.h \
    ./server.h \
    ../shared/shared.h
SOURCES += ./main.cpp \
    ./nonblockserver.cpp \
    ./server.cpp
FORMS += ./nonblockserver.ui
RESOURCES += nonblockserver.qrc
