a.o : x.x y.y z.z
	@echo a.o : x.x y.y z.z
	@echo 'S<' $<
	@echo 'S@' $@
	@echo 'S?' $?
	@echo 'S*' $*
	@echo 'S^' $^

	@echo 'S~' $~
	@echo 'S`' $`
	@echo 'S!' $!
	@echo 'S#' $#
	@echo 'S%' $%
	@echo 'S&' $&
	@echo 'S|' $|
	@echo 'S>' $>
