olark.declare({name:"CalloutBubble",version:"1.0",startup:function(l,d){function o(a,b){var d={duration:1E3,interval:10,from:0,to:100,easingFunc:function(a,c,b){var d=0;d=(b/=1)<1/2.75?1*7.5625*b*b+0:b<2/2.75?1*(7.5625*(b-=1.5/2.75)*b+0.75)+0:b<2.5/2.75?1*(7.5625*(b-=2.25/2.75)*b+0.9375)+0:1*(7.5625*(b-=2.625/2.75)*b+0.984375)+0;return a+(c-a)*d}},f;for(f in b)b.hasOwnProperty(f)&&(d[f]=b[f]);var e=[],g=d.duration/d.interval;for(f=0;f<g;++f)e.push(d.easingFunc(d.from,d.to,f/g));for(f=0;f<e.length;++f)(function(){setTimeout(function(){a.style.height=
parseInt(e.shift())+"px"},d.interval*f)})(e[f])}function p(a,b,d,f){if(a)if(!b&&!d){var e=new Image,g=!1,h=function(){d=parseInt(e.height);b=parseInt(e.width);!g&&d&&b&&(f(b,d),g=!0)};e.onload=h;e.src=a;h()}else b&&d&&f(b,d);else f(b,d)}function s(c){p(a.BUBBLE_IMAGE_URL,a.BUBBLE_WIDTH,a.BUBBLE_HEIGHT,function(b,d){a.BUBBLE_HEIGHT=d||a.DEFAULT_HEIGHT;a.BUBBLE_WIDTH=b||a.DEFAULT_WIDTH;p(a.BUBBLE_IMAGE_URL_OFFLINE,a.BUBBLE_WIDTH_OFFLINE,a.BUBBLE_HEIGHT_OFFLINE,function(b,d){a.BUBBLE_HEIGHT_OFFLINE=
d||a.DEFAULT_HEIGHT;a.BUBBLE_WIDTH_OFFLINE=b||a.DEFAULT_WIDTH;a.BUBBLE_BOTTOM_OFFSET=a.BUBBLE_BOTTOM_OFFSET||0;a.BUBBLE_TOP_OFFSET=a.BUBBLE_TOP_OFFSET||0;a.BUBBLE_LEFT_OFFSET=a.BUBBLE_LEFT_OFFSET||a.OFFSET.left;a.BUBBLE_RIGHT_OFFSET=a.BUBBLE_RIGHT_OFFSET||a.OFFSET.right;a.BUBBLE_BOTTOM_OFFSET_OFFLINE=0;a.BUBBLE_TOP_OFFSET_OFFLINE=0;a.BUBBLE_LEFT_OFFSET_OFFLINE=a.BUBBLE_LEFT_OFFSET_OFFLINE||a.OFFSET_OFFLINE.left;a.BUBBLE_RIGHT_OFFSET_OFFLINE=a.BUBBLE_RIGHT_OFFSET_OFFLINE||a.OFFSET_OFFLINE.right;c()})})}
function t(){u.id="habla-callout-container";e.id="habla-callout-bubble-anchor";i.id="habla-callout-bubble-anchor-offline";g.id="olark-callout-bubble";h.id="olark-callout-bubble-offline";e.href="#";i.href="#";(function(c){c=c||function(){return!1};e.onclick=function(){a.CLICKED.set(!0);l.box.expand();a.HIDE_WHEN_CLICKED&&a.CLICKED.get()&&m();return c()}})(e.onclick);(function(c){c=c||function(){return!1};j.onclick=function(){a.X_CLICKED.set(!0);if(a.HIDE_WHEN_X_CLICKED&&a.X_CLICKED.get()){m();if(!b)var b=
window.event;b.cancelBubble=!0;b.stopPropagation&&b.stopPropagation()}return c()}})(j.onclick);(function(c){c=c||function(){return!1};i.onclick=function(){a.CLICKED.set(!0);l.box.expand();a.HIDE_WHEN_CLICKED&&a.CLICKED.get()&&m();return c()}})(i.onclick);(function(c){c=c||function(){return!1};k.onclick=function(b){a.X_CLICKED.set(!0);if(a.HIDE_WHEN_X_CLICKED&&a.X_CLICKED.get()){m();if(!b)b=window.event;b.cancelBubble=!0;b.stopPropagation&&b.stopPropagation()}return c()}})(k.onclick);window.addEventListener&&
!window.opera?(g.addEventListener("mouseover",function(){j.className="olark-callout-bubble-close-button"},!1),h.addEventListener("mouseover",function(){k.className="olark-callout-bubble-close-button"},!1)):window.attachEvent?(g.attachEvent("onmouseover",function(){j.className="olark-callout-bubble-close-button"}),h.attachEvent("onmouseover",function(){k.className="olark-callout-bubble-close-button"})):(g.onmouseover=function(){j.className="olark-callout-bubble-close-button"},h.onmouseover=function(){k.className=
"olark-callout-bubble-close-button"});window.addEventListener&&!window.opera?(g.addEventListener("mouseout",function(){j.className=""},!1),h.addEventListener("mouseout",function(){k.className=""},!1)):window.attachEvent?(g.attachEvent("onmouseout",function(){j.className=""}),h.attachEvent("onmouseout",function(){k.className=""})):(h.onmouseout=function(){k.className=""},g.onmouseout=function(){j.className=""});e.appendChild(g);g.appendChild(j);i.appendChild(h);h.appendChild(k)}function q(){var c=
!a.BUBBLE_IMAGE_URL||a.BUBBLE_IMAGE_URL=="";a.HIDE_WHEN_CLICKED&&a.CLICKED.get()||c?m():a.HIDE_WHEN_X_CLICKED&&a.X_CLICKED.get()?m():(e.style.display="block",i.style.display="none");c=e.firstChild;if(!a.SLID.get()&&a.BUBBLE_SLIDE_EFFECT)c.style.visibility="hidden",c.style.height=0;g.style.display="block";h.style.display="none";!a.SLID.get()&&a.BUBBLE_SLIDE_EFFECT&&v()}function r(){var c=!a.BUBBLE_IMAGE_URL_OFFLINE||a.BUBBLE_IMAGE_URL_OFFLINE=="";a.HIDE_WHEN_CLICKED&&a.CLICKED.get()||c?m():(e.style.display=
"none",i.style.display="block")}function m(){e.style.display="none";i.style.display="none";var a=document.getElementById("habla_compressed_div");a.style.height=null;a.style.width=null}function v(){var c=e.firstChild,b={to:parseInt(a.BUBBLE_HEIGHT),duration:750};setTimeout(function(){c.style.visibility="visible";o(c,b);n()},2E3);a.SLID.set(!0)}function n(){clearTimeout(a.IDLE_TIMEOUT);a.IDLE_TIMEOUT=setTimeout(function(){var c={from:parseInt(a.BUBBLE_HEIGHT)+20,to:parseInt(a.BUBBLE_HEIGHT),duration:750};
o(e.firstChild,c);n()},2E4)}var a={};a.DEFAULT_WIDTH=164;a.DEFAULT_HEIGHT=153;a.PROTOCOL=document.location.protocol=="https:"?"https:":"http:";a.DEFAULT_IMAGE_PATH=a.PROTOCOL+"//static.olark.com/images/thisisolark-trans.png";a.CLOSE_BUTTON_IMAGE_PATH=a.PROTOCOL+"//static.olark.com/images/close.png";a.BUBBLE_IMAGE_URL=d.CalloutBubble.bubble_image_url!=void 0?d.CalloutBubble.bubble_image_url:a.DEFAULT_IMAGE_PATH;a.BUBBLE_IMAGE_URL_OFFLINE=d.CalloutBubble.offline_bubble_image_url||d.CalloutBubble.bubble_image_url_offline||
void 0;a.BUBBLE_HEIGHT=d.CalloutBubble.bubble_height||void 0;a.BUBBLE_WIDTH=d.CalloutBubble.bubble_width||void 0;a.BUBBLE_HEIGHT_OFFLINE=d.CalloutBubble.bubble_height_offline||void 0;a.BUBBLE_WIDTH_OFFLINE=d.CalloutBubble.bubble_width_offline||void 0;a.BUBBLE_BOTTOM_OFFSET=d.CalloutBubble.bubble_bottom_offset||void 0;a.BUBBLE_TOP_OFFSET=d.CalloutBubble.bubble_top_offset||void 0;a.BUBBLE_RIGHT_OFFSET=d.CalloutBubble.bubble_right_offset||void 0;a.BUBBLE_LEFT_OFFSET=d.CalloutBubble.bubble_left_offset||
void 0;a.BUBBLE_BOTTOM_OFFSET_OFFLINE=d.CalloutBubble.bubble_bottom_offset_offline||void 0;a.BUBBLE_TOP_OFFSET_OFFLINE=d.CalloutBubble.bubble_top_offset_offline||void 0;a.BUBBLE_RIGHT_OFFSET_OFFLINE=d.CalloutBubble.bubble_right_offset_offline||void 0;a.BUBBLE_LEFT_OFFSET_OFFLINE=d.CalloutBubble.bubble_left_offset_offline||void 0;a.OFFSET=d.CalloutBubble.offset||{};a.OFFSET_OFFLINE=d.CalloutBubble.offset_offline||{};a.OFFSET.top=a.OFFSET.top||0;a.OFFSET.bottom=a.OFFSET.bottom||0;a.OFFSET.left=a.OFFSET.left||
0;a.OFFSET.right=a.OFFSET.right||0;a.OFFSET_OFFLINE.top=a.OFFSET_OFFLINE.top||0;a.OFFSET_OFFLINE.bottom=a.OFFSET_OFFLINE.bottom||0;a.OFFSET_OFFLINE.left=a.OFFSET_OFFLINE.left||0;a.OFFSET_OFFLINE.right=a.OFFSET_OFFLINE.right||0;a.BUBBLE_SLIDE_EFFECT=d.CalloutBubble.slide||!1;a.HIDE_WHEN_CLICKED=d.CalloutBubble.hide_when_clicked||!1;a.HIDE_WHEN_X_CLICKED=d.CalloutBubble.hide_when_x_clicked||!0;a.IDLE_TIMEOUT=void 0;a.CLICKED=l.data.getConversationObject({key:"bubble-clicked",initialValue:!1});a.X_CLICKED=
l.data.getConversationObject({key:"bubble-x-clicked",initialValue:!1});a.LOADED=!1;a.SLID=l.data.getConversationObject({key:"bubble-slid",initialValue:!1});a.SSL_PAGE=a.PROTOCOL=="https:";if(a.SSL_PAGE){if(a.BUBBLE_IMAGE_URL)a.BUBBLE_IMAGE_URL=a.BUBBLE_IMAGE_URL.replace("http:","https:");if(a.BUBBLE_IMAGE_URL_OFFLINE)a.BUBBLE_IMAGE_URL_OFFLINE=a.BUBBLE_IMAGE_URL_OFFLINE.replace("http:","https:")}var w=document.compatMode=="BackCompat",u=document.createElement("div"),e=document.createElement("a"),
i=document.createElement("a"),g=document.createElement("div"),h=document.createElement("div"),j=document.createElement("div"),k=document.createElement("div");l.chat.onOperatorsAvailable(function(){a.LOADED&&(a.HIDE_WHEN_CLICKED&&a.CLICKED.set(!1),a.BUBBLE_SLIDE_EFFECT&&a.SLID.set(!1),q())});l.chat.onOperatorsAway(function(){r()});l.chat.onReady(function(){t();s(function(){var c=document.getElementById("habla_compressed_div"),b=document.getElementById("habla_panel_div");if(window.opera)c.style.height=
parseInt(a.BUBBLE_HEIGHT)+"px";if(w)c.style.height=parseInt(a.BUBBLE_HEIGHT+10)+"px",c.style.width=parseInt(b.offsetWidth)+"px";b=["#habla_window_div {z-index:5000;}#habla_window_div #habla-callout-bubble-anchor,#habla_window_div #habla-callout-bubble-anchor-offline {margin: 0px;padding: 0px;border: 0px;}#habla_compressed_div {position: relative;}#habla_window_div .olark-callout-bubble-close-button {height: 20px;width: 20px;position: absolute;top: 0px;right: 0px;","background: transparent url("+a.CLOSE_BUTTON_IMAGE_PATH+
") top right no-repeat;","z-index:5001}#habla_window_div #olark-callout-bubble,#habla_window_div #olark-callout-bubble-offline {position: absolute;cursor: pointer;}#habla_window_div #olark-callout-bubble {","height: "+parseInt(a.BUBBLE_HEIGHT)+"px;","width: "+parseInt(a.BUBBLE_WIDTH)+"px;","}.olrk-fixed-bottom #olark-callout-bubble {",a.BUBBLE_IMAGE_URL?"background: transparent url("+a.BUBBLE_IMAGE_URL+") center top no-repeat;":"","z-index:5000;position:relative;}.olrk-fixed-top #olark-callout-bubble {",
a.BUBBLE_IMAGE_URL?"background: transparent url("+a.BUBBLE_IMAGE_URL+") center bottom no-repeat;":"","z-index:5000;position:relative;}#habla_window_div #olark-callout-bubble-offline {","height: "+parseInt(a.BUBBLE_HEIGHT_OFFLINE)+"px;","width: "+parseInt(a.BUBBLE_WIDTH_OFFLINE)+"px;","}.olrk-fixed-bottom #olark-callout-bubble-offline {",a.BUBBLE_IMAGE_URL_OFFLINE?"background: transparent url("+a.BUBBLE_IMAGE_URL_OFFLINE+") center top no-repeat;":"","z-index:5000;position:relative;}.olrk-fixed-top #olark-callout-bubble-offline {",
a.BUBBLE_IMAGE_URL_OFFLINE?"background: transparent url("+a.BUBBLE_IMAGE_URL_OFFLINE+") center bottom no-repeat;":"","z-index:5000;position:relative;}.olrk-fixed-top #olark-callout-bubble {","top: "+parseInt(a.BUBBLE_TOP_OFFSET)+"px;","}.olrk-fixed-bottom #olark-callout-bubble {","bottom: "+parseInt(a.BUBBLE_BOTTOM_OFFSET)+"px;","}.olrk-fixed-left #olark-callout-bubble {","right: "+parseInt(a.BUBBLE_LEFT_OFFSET)+"px;","}.olrk-fixed-right #olark-callout-bubble {","left: "+parseInt(a.BUBBLE_RIGHT_OFFSET)+
"px;","}.olrk-fixed-left .olrk-left-align #olark-callout-bubble {","left: "+parseInt(a.BUBBLE_RIGHT_OFFSET)+"px;","}.olrk-fixed-top #olark-callout-bubble-offline {","top: "+parseInt(a.BUBBLE_TOP_OFFSET_OFFLINE)+"px;","}.olrk-fixed-bottom #olark-callout-bubble-offline {","bottom: "+parseInt(a.BUBBLE_BOTTOM_OFFSET_OFFLINE)+"px;","}.olrk-fixed-left #olark-callout-bubble-offline {","right: "+parseInt(a.BUBBLE_LEFT_OFFSET_OFFLINE)+"px;","}.olrk-fixed-right #olark-callout-bubble-offline {","left: "+parseInt(a.BUBBLE_RIGHT_OFFSET_OFFLINE)+
"px;","}.olrk-fixed-left .olrk-left-align #olark-callout-bubble-offline {","left: "+parseInt(a.BUBBLE_RIGHT_OFFSET_OFFLINE)+"px;","}#habla_window_div a:hover {background-color:transparent;}#habla_available_div {display: none;}"].join("");c=document.createElement("style");c.type="text/css";c.styleSheet?c.styleSheet.cssText=b:c.appendChild(document.createTextNode(b));b=document.getElementsByTagName("head")[0];b.insertBefore(c,b.firstChild);if(!a.SLID.get()&&a.BUBBLE_SLIDE_EFFECT)c=e.firstChild,c.style.visibility=
"hidden",c.style.height=0;c=document.getElementById("habla_compressed_div");c.appendChild(e);c.appendChild(i);hbl.client.opavailable&&hbl.client.opstatus!="away"?q():r();if(a.BUBBLE_SLIDE_EFFECT)try{window.addEventListener("mousemove",n,!1)}catch(d){try{document.attachEvent("onmousemove",n)}catch(f){}}a.LOADED=!0})})}});
