olark.declare({name:"Cobrowse",version:"1.0",startup:function(g,h){function t(a){var e=curtop=0;if(a.offsetParent){do e+=a.offsetLeft,curtop+=a.offsetTop;while(a=a.offsetParent)}return{x:e,y:curtop}}function u(a,e){function d(){if(document.body&&document.body.scrollTop)return document.body.scrollTop;if(document.documentElement&&document.documentElement.scrollTop)return document.documentElement.scrollTop;if(window.pageYOffset)return window.pageYOffset;return 0}function f(){var a=d();i++;window.scrollTo(0,
a+g);i<b?setTimeout(f,10):e()}var b=25,c=d(),g=(a-c)/b,i=0;f()}function v(a,e,d){var f=o[a]||null,b=document.createElement("div"),c=document.createElement("img");f?(a=t(f),b.className="olark-cobrowse-client-pointer",b.style.left=a.x+e+"px",b.style.top=a.y+d+"px",c.setAttribute("src",w),c.style.left=-1*x/2+"px",c.style.top=-1*y/2+"px",b.appendChild(c),b.onclick=function(){b.className+=" olark-cobrowse-client-pointer-dismissed"},u(a.y+d-200,function(){setTimeout(function(){(document.body||document.getElementsByTagName("body")[0]).appendChild(b)},
500)})):window.console&&window.console.warn&&window.console.warn("[olark] unable to spotlight element with id="+a)}function z(){function a(a){var c=Math.random().toString().replace(".","");a.setAttribute("cobrowseid",c);o[c]=a}var e,d;try{e=document.all||document.getElementsByTagName("body")[0].getElementsByTagName("*")}catch(f){throw Error("[olark] unable to get a handle on all document elements: "+f);}for(d=0;d<e.length;d++)a(e[d]);a(document.body||document.getElementsByTagName("body")[0])}var k=
h.Cobrowse.server||"https://olarkengine.appspot.com",A=k.replace("https:",window.location.protocol=="https:"?"https:":"http:"),w=h.Cobrowse.pointer_url||k+"/a/cobrowse/static/pointer.png",x=h.Cobrowse.pointer_width||200,y=h.Cobrowse.pointer_height||200,o={},j=g.data.getConversationObject({key:"cobrowseToken",initialValue:null}),B=window.olark.__core.framestorewithjson.framesocket,p=4E3;(function(){var a=document.createElement("style"),e=document.createTextNode(".olark-cobrowse-client-pointer{\nposition: absolute;\ndisplay: block;\nwidth: 50px;\nheight: 50px;\npadding: 0px;\nmargin: 0px;\nborder-width: 0px;\n}\n.olark-cobrowse-client-pointer img{\nposition: absolute;\ndisplay: block;\npadding: 0px;\nmargin: 0px;\nborder-width: 0px;\n}\n.olark-cobrowse-client-pointer-dismissed{\ndisplay: none;\n}");
a.setAttribute("type","text/css");a.styleSheet?a.styleSheet.cssText=e.nodeValue:a.appendChild(e);document.getElementsByTagName("head")[0].appendChild(a)})();olark("api.boot.onIdentityReady",function(a,e,d){function f(b){var g=j.get(),l,r,m,s,q=0;if(h){z();try{l=document.documentElement.innerHTML}catch(o){l=document.documentElement.outerHTML}m=Math.ceil(l.length/p);for(c.send("prepareHtmlChunks,"+m);m>0;)s=l.slice(q,q+p),q+=p,m--,c.send("appendHtmlChunk,"+escape(s));c.send("setBaseHref,"+document.location.protocol+
"//"+document.location.host);c.send("setUrl,"+document.location.href);c.send("setOlarkIdentity,"+[a,e,d].join(","));c.send("syncToServer");b&&n.push(function(){r=A+"/a/cobrowse/view?token="+g;b(r)})}else i.push(function(){f(b)}),c=c||B.connect(k+"/a/cobrowse/socket?token="+g,function(a){h=!0;if(a.data=="ready")for(h=!0;i.length;)i.shift()();else if(/^handleError/.test(a.data))throw Error("[olark] remote error: "+unescape(a.data.replace("handleError,","")));else if(a.data=="syncFinished")for(;n.length;)n.shift()()})}
function b(){var a=j.get();a&&window.olark.__core.async_script_load({url:k+"/a/cobrowse/pending?token="+a+"&cachebreaker="+Math.random()})}var c,h,i=[],n=[];j.get()&&olark("api.boot.onWindowLoad",function(){b();setTimeout(function(){f()},2E3)});window.addEventListener?(window.addEventListener("beforeunload",b,!1),window.addEventListener("unload",b,!1)):(window.attachEvent("onbeforeunload",b),window.attachEvent("onunload",b));olark("api.chat.onCommandFromOperator",function(a){var b=!1;if(a.command.name==
"see")try{j.get()||j.set(Math.random().toString().replace(".","")+e),g.chat.sendNotificationToOperator("connecting with the visitor's browser..."),f(function(a){b=!0;g.chat.sendNotificationToOperator("see what they see ==> "+a)}),setTimeout(function(){b||g.chat.sendNotificationToOperator("looks like connecting with the browser is going slowly, please contact us to see what we can do: beta+cobrowsing@olark.com")},11E3)}catch(c){window.console&&window.console.warn&&window.console.warn("[olark] unable to start cobrowsing session:",
c.toString()),g.chat.sendNotificationToOperator("unable to start cobrowsing session, please contact us to see what we can do: beta+cobrowsing@olark.com")}else if(a.command.name=="cobrowseevent"){var d=a.command.body.split(" ");a=d[1];var h=parseInt(d[2]);d=parseInt(d[3]);v(a,h,d)}else a.command.name=="cobrowserefresh"&&f()})})}});
