######################################################################
# Automatically generated by qmake (2.01a) Sun 11. Jul 17:35:53 2010
######################################################################

TEMPLATE = app
TARGET = progressDialog
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += consumer.h producer.h progressdialog.h
FORMS += progressdialog.ui
SOURCES += consumer.cpp main.cpp producer.cpp progressdialog.cpp
RESOURCES += progressdialog.qrc
